---
spring:
        application:
                name: eureka-client-${spring.profiles.active}
eureka:
        instance: 
                instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
        client:
                serviceUrl:
                        defaultZone: http://localhost:8761/                

---
spring:
        profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
        profiles: article
words: a,the

---
spring:
        profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
        profiles: subject
words: I,You,He,She,It

---
spring:
        profiles: verbs
words: ran,knew,had,saw,bought
